AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Cart service is part of the ACME Serverless Shop. The goal of this specific service is to keep track of carts and items in the different carts.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  ClearCart:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-cart-clear
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: ClearCart 
      Description: A Lambda function to clear the cart of a user
      MemorySize: 256
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: "Cart"
      Environment:
        Variables:
          TABLE: "Cart"
      Events:
        ClearCartAPI:
          Type: Api
          Properties:
            Path: /cart/clear/{userid}
            Method: GET
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  ClearCartLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "ClearCart"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ClearCart]]

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  ClearCartURL:
    Description: "API Gateway endpoint URL to clear a cart"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cart/clear/{userid}"