AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Cart service is part of the ACME Serverless Shop. The goal of this specific service is to keep track of carts and items in the different carts.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  Cart: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "UserID"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "UserID"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "10"
      TableName: "Cart"

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  CartTableARN:
    Description: ARN for the Cart DynamoDB Table
    Value: !GetAtt Cart.Arn